### ISSUE TITLE
P01 term for Area

### ISSUE THREAD

**Issue by peterdesmet** [inbo/esas2obis#19]
Area is defined as:

> Area of sea surveyed during the observation bin in km². Can only remain empty if Distance is used.

There are two existing terms that come close:

## Sample area (aircraft survey)

- http://vocab.nerc.ac.uk/collection/P01/current/SAMPARAC/
- The areal extent of the portion of the Earth's surface included in a given sampling event (such as an animal count) from an aircraft
- Related to square km

## Area (representative)

- http://vocab.nerc.ac.uk/collection/P01/current/NEWCXX01/
- The area over which the measurements made are considered to be representative.
- Relate to square m

The first one looks great, but @nicolasvanermen, I assume ESAS data could use `area` for ship based observations as well? Or is the match close enough?

**Comment by peterdesmet** [comment]
Note that it is not https://vocab.nerc.ac.uk/collection/Q01/current/Q0100017/ "Sampling device aperture surface area"

**Comment by nicolasvanermen** [comment]
Note that the second relates to square m instead of km...
These are two seperate vocabs, does this imply two columns, or can they be integrated in one field? 
And is it necessary to "contain" everything in a vocabulary? Even such generic fields as distance and area?

**Comment by peterdesmet** [comment]
These terms are not controlled vocabularies, but standardized description of measurement methods. It’s good to link to one of if we can, because it allows to cross-dataset standardization.

In these issues I describe which one could apply. If we can’t find a good match, that is ok too: then we don’t link.

**Comment by peterdesmet** [comment]
@rubenpp7 @pieterprovoost see the issue description. We have a term "area" in ESAS, that describes "Area of sea surveyed during the observation bin in km²". This can be done from aircraft or boat. Would you say that maps sufficiently to "Sample area (aircraft survey)" at http://vocab.nerc.ac.uk/collection/P01/current/SAMPARAC/ for us to use that URL as a `measurementTypeID`

**Comment by pieterprovoost** [comment]
@peterdesmet But these are not (all) aerial surveys, right? In that case we will need another term. 

@gwemon

**Comment by gwemon** [comment]
Thanks for pinging me @pieterprovoost 
We could create a more generic term than SAMPARAC for "Area of sampling event"?  This will be created using our semantic model so re-using [Area](http://vocab.nerc.ac.uk/collection/S06/current/S0600146/) as defined in S06  and adding a new term "sampling event" to the S29 vocabulary to give "Area of sampling event". Once we have this new term defined we we also be able to harmonise existing sampling event-related P01 terms reusing the same components. i.e. SAMPARAC which is a term that is still not expressed using our semantic model will become "Area of sampling event by aircraft survey". Would that work for you?
Also bear in mind that the units we associate with a P01 concept in the NVS is a BODC unit only. Unfortunately we cannot change this because too much legacy is dependent on it. However you must define the unit in your dataset independently of the P01 term and you can use whichever unit you want providing it has the same dimension (i.e. L^2 in this case)

**Comment by peterdesmet** [comment]
I for one support a more generic `Area of sampling event` term. 👍  We can indeed define our unit (km<sup>2</sup>) separately.

**Comment by peterdesmet** [comment]
Once the term becomes available at NERC, `measurementTypeID` in the following code should be updated to reference it:

https://github.com/inbo/esas2obis/blob/ba1a98396963b668b38f35383f4eb03ad549ab51/sql/dwc_emof.sql#L246-L256

**Comment by peterdesmet** [comment]
`measurementTypeID` for "Area" updated to `https://vocab.nerc.ac.uk/collection/P01/current/SAMPARAX/` in ba1a983
