### ISSUE TITLE
Get taxonomic information

### ISSUE THREAD

**Issue by peterdesmet** [inbo/esas2obis#27]

**Comment by peterdesmet** [comment]
@pieterprovoost @rubenpp7 how should I populate `scientificName`: with the **scientific name as found in the source database** (not always valid, sometimes even empty) or the one that matches the AphiaID? Note that I will always add a `scientificNameID` with an `AphiaID` that is the closest match in WoRMS.

Examples:

Source scientific name | common name (not mapped) | AphiaID | WoRMS scientific name
--- | --- | --- | ---
Bulweria fallax | Jouanin's Petrel | 212650 | Bulweria fallax
Calonectris diomedea / borealis | Scopoli's / Cory's Shearwater | 137062 | Calonectris
\- | unidentified petrel | 136998 | Procellariidae
\- | unidentified fish | 11676 | Pisces (unaccepted taxon in WoRMS)

See all possible values at: https://esas-docs.ices.dk/species/

**Comment by pieterprovoost** [comment]
@peterdesmet Current OBIS guidelines are to populate `scientificName` with the exact name as found in the source. But I'll discuss with our taxonomy task team because `verbatimIdentification` may be more appropriate for that. Also, please use the full LSID for `scientificNameID`. LSIDs can be for unaccepted species, we resolve to accepted species during indexing.
